# Generated by Django 5.0.14 on 2026-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='full_name',
            field=models.CharField(default='P Jayant Kumar', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='title',
            field=models.CharField(default='Full Stack Developer, DevOps Engineer, and Tech Enthusiast', max_length=100),
        ),
    ]
