# Generated by Django 5.0.14 on 2026-07-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_siteconfig_full_name_alter_siteconfig_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
